### ISSUE TITLE
Wrong detect in python

### ISSUE THREAD

**Issue by YaCenturion** [AtomMaterialUI/color-highlighter#137]
Just regular tuple detected as color.

Example:

> def wrong_detect():
>     for x in (0, 1, 2):
>         print(x)

PyCharm 2023:
<img width="204" alt="Screenshot 2023-11-02 092737" src="https://github.com/mallowigi/color-highlighter/assets/65896249/3f7db937-2626-4985-bfc8-f52251f83d4b">

Can you fix this? Thanks

**Comment by mallowigi** [comment]
![CleanShot 2024-09-13 at 21 19 21](https://github.com/user-attachments/assets/6e68443b-da12-4063-b635-df4b371582f3)
