### ISSUE TITLE
PyCharm CSS File support

### ISSUE THREAD

**Issue by dhyanKaro** [AtomMaterialUI/color-highlighter#138]
I just want my colors to be highlighted when I have a css file open in pycharm.

![Screenshot 2023-11-06 at 6 00 18 PM](https://github.com/mallowigi/color-highlighter/assets/112676875/9e5cb367-2f99-4191-a095-15199184e43d)

Did this too, still nothing:

![Screenshot 2023-11-06 at 6 04 48 PM](https://github.com/mallowigi/color-highlighter/assets/112676875/4cbfd4ca-032a-4bcf-9ec8-421eb51909e6)

**Comment by mallowigi** [comment]
I think CSS files are handled via the CSS settings
<img width="2168" alt="CleanShot 2023-11-06 at 15 35 54@2x" src="https://github.com/mallowigi/color-highlighter/assets/5015756/ff61b61e-d0df-4914-aaee-07f276f6d679">

**Comment by dhyanKaro** [comment]
You must have a different version than me.

![Screenshot 2023-11-06 at 10 32 03 PM](https://github.com/mallowigi/color-highlighter/assets/112676875/a785bb86-a327-4a96-a416-817abc7f90cb)

**Comment by mallowigi** [comment]
You probably don't have the CSS plugin enabled

**Comment by FleetAdmiralJakob** [comment]
I think this is a bug since it not works in CSS for me
