### ISSUE TITLE
CSS Function Parsing

### ISSUE THREAD

**Issue by dp1140a** [AtomMaterialUI/color-highlighter#149]
Ina  css file this will correctly display:
`background-color: rgb(30 66 159);`
![image](https://github.com/mallowigi/color-highlighter/assets/5685054/fe7b3f6c-a712-4370-8f1f-88177606ea06)

But this will not:
`background-color: rgb(30 66 159 / var(--tw-bg-opacity));`
![image](https://github.com/mallowigi/color-highlighter/assets/5685054/43275a8a-0ea4-4657-b547-2f5952fa2a6d)

**Comment by mallowigi** [comment]
Css files are handled natively by the CSS plugin. For feature requests, please open an issue in JetBrains.
