### ISSUE TITLE
JS file only partially displays colors

### ISSUE THREAD

**Issue by dp1140a** [AtomMaterialUI/color-highlighter#150]
I have a js file (Its actually the Tailwind colors.js file)  The colors only partially display:

Here is a snippet of the file
```javascript
const _default = {
    inherit: "inherit",
    current: "currentColor",
    transparent: "transparent",
    black: "#000",
    white: "#fff",
    slate: {
        50: "#f8fafc",
        100: "#f1f5f9",
        200: "#e2e8f0",
        300: "#cbd5e1",
        400: "#94a3b8",
        500: "#64748b",
        600: "#475569",
        700: "#334155",
        800: "#1e293b",
        900: "#0f172a",
        950: "#020617"
    },
```

This displays as:
![image](https://github.com/mallowigi/color-highlighter/assets/5685054/1a67a9b8-9093-415c-8c7a-ffc1b4c5af5e)

**Comment by mallowigi** [comment]
![CleanShot 2024-09-13 at 21 24 41](https://github.com/user-attachments/assets/ea51a588-d096-46e0-8d8e-4d96af5c15cd)

looks good to me... 

what are your settings?
