### ISSUE TITLE
Add a parser for Compose Color(color: Long)

### ISSUE THREAD

**Issue by Qw4z1** [AtomMaterialUI/color-highlighter#152]
The standard way to specify colors in Jetpack Compose is by using a 32-bit ARGB hex value. The parser currently interprets the value as a normal hex color, which breaks the preview. 

For example, this is how I would specify blue `val blue = Color(0xFF0000FF)`, but the plugin shows this as red.

There are of cource other ways to specify colors, but since this is the standard all examples and generated code comes in this format.

Additional context: This is the implementation of the Color function in Compose

```
/**
 * Creates a new [Color] instance from an ARGB color int.
 * The resulting color is in the [sRGB][ColorSpaces.Srgb]
 * color space. This is useful for specifying colors with alpha
 * greater than 0x80 in numeric form without using [Long.toInt]:
 *
 *     val color = Color(0xFF000080)
 *
 * @param color The 32-bit ARGB color int to create a <code>Color</code>
 * from
 * @return A non-null instance of {@link Color}
 */
@Stable
fun Color(color: Long): Color {
    return Color(value = (color.toULong() and 0xffffffffUL) shl 32)
}
```

**Comment by mallowigi** [comment]
![CleanShot 2024-09-13 at 21 27 02](https://github.com/user-attachments/assets/2ff769d7-6a03-4948-8a7a-ef11b3f865a8)
