### ISSUE TITLE
Terrible performance

### ISSUE THREAD

**Issue by palexdev** [AtomMaterialUI/color-highlighter#155]
**Describe the bug**
After some investigation by the JetBrains team, we discovered that this plugin was the cause of high CPU spikes while typing and consequently system stuttering

**To Reproduce**
1. Install the plugin
2. Write some code, it's a bit hard to reproduce because it seems situational
3. Observe the CPU usage

**Expected Behavior**
I do not expect a simple plugin like this to have this much impact on performance, the code needs to be optimized

**Environment**
Does not matter, it happens on any OS. However, I noticed that the issue is more severe and frequent on IntelliJ IDEA 2024.
Plugin version: latest (18.0.0)
Other plugins: initially we thought Grazie Pro could be the culprit too, but I can't reproduce the issue by enabling only that. The issue appears when this plugin is enabled, no matter in what configuration

**Useful Links**
Here is the link to the YouTrack issue: [IDEA-354009](https://youtrack.jetbrains.com/issue/IDEA-354009/High-CPU-usage-spikes)

**Comment by mallowigi** [comment]
I'm not very strong in performance issues. I'm a one-man team so any help is appreciated. Closing this because it's unlikely I'll have the time to do it myself.
