### ISSUE TITLE
Does not correctly show decimal colors

### ISSUE THREAD

**Issue by milosworks** [AtomMaterialUI/color-highlighter#175]
**Describe the bug**

**To Reproduce**

1. Grab a color hex (ex: #A9A9A9)
2. Convert it to its decimal form (ex: 11119017)

**Expected Behavior**

Should show a gray color

**Environment**

IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 22, 2024
Licensed to REDACTED
Subscription is active until December 7, 2024.
For educational use only.
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  debugger.new.tool.window.layout=true
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  some.awesome (1.15)
  re.bizar.celestial (0.2.0)
  com.intellij.plugins.vscodekeymap (242.20224.385)
  com.mallowigi.colorHighlighter (18.1.0)
  me.shedaniel.architectury (1.6.3)
  com.mallowigi (97.0.0)
  dev.azn9.plugins.discord (2.1.4.242)
Kotlin: 242.23726.103-IJ

**Screenshots**

![image](https://github.com/user-attachments/assets/be955ff1-afdd-478d-9d58-d5a47fc2cb61)
If i use hex it works
![image](https://github.com/user-attachments/assets/dee58c75-e0ae-45ea-9472-e1cd9f036121)

**Comment by mallowigi** [comment]
Sorry, I don't plan on supporting this format
